[1mdiff --git a/config/settings.py b/config/settings.py[m
[1mdeleted file mode 100644[m
[1mindex 9bbd43c..0000000[m
[1m--- a/config/settings.py[m
[1m+++ /dev/null[m
[36m@@ -1,141 +0,0 @@[m
[31m-"""[m
[31m-Django settings for config project.[m
[31m-[m
[31m-Generated by 'django-admin startproject' using Django 5.1.2.[m
[31m-[m
[31m-For more information on this file, see[m
[31m-https://docs.djangoproject.com/en/5.1/topics/settings/[m
[31m-[m
[31m-For the full list of settings and their values, see[m
[31m-https://docs.djangoproject.com/en/5.1/ref/settings/[m
[31m-"""[m
[31m-[m
[31m-from pathlib import Path[m
[31m-import os[m
[31m-[m
[31m-# Build paths inside the project like this: BASE_DIR / 'subdir'.[m
[31m-BASE_DIR = Path(__file__).resolve().parent.parent[m
[31m-[m
[31m-[m
[31m-[m
[31m-[m
[31m-[m
[31m-# Quick-start development settings - unsuitable for production[m
[31m-# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/[m
[31m-[m
[31m-# SECURITY WARNING: keep the secret key used in production secret![m
[31m-SECRET_KEY = 'django-insecure-39kla+k5i)j7y48e+o9dda9e=ae#ci%kysmjrcj+l8&vfo6o-2'[m
[31m-[m
[31m-# SECURITY WARNING: don't run with debug turned on in production![m
[31m-DEBUG = True[m
[31m-[m
[31m-ALLOWED_HOSTS = ['3.39.196.102'][m
[31m-[m
[31m-[m
[31m-# Application definition[m
[31m-[m
[31m-INSTALLED_APPS = [[m
[31m-    'django.contrib.admin',[m
[31m-    'django.contrib.auth',[m
[31m-    'django.contrib.contenttypes',[m
[31m-    'django.contrib.sessions',[m
[31m-    'django.contrib.messages',[m
[31m-    'django.contrib.staticfiles',[m
[31m-][m
[31m-[m
[31m-MIDDLEWARE = [[m
[31m-    'django.middleware.security.SecurityMiddleware',[m
[31m-    'django.contrib.sessions.middleware.SessionMiddleware',[m
[31m-    'django.middleware.common.CommonMiddleware',[m
[31m-    'django.middleware.csrf.CsrfViewMiddleware',[m
[31m-    'django.contrib.auth.middleware.AuthenticationMiddleware',[m
[31m-    'django.contrib.messages.middleware.MessageMiddleware',[m
[31m-    'django.middleware.clickjacking.XFrameOptionsMiddleware',[m
[31m-][m
[31m-[m
[31m-ROOT_URLCONF = 'config.urls'[m
[31m-[m
[31m-TEMPLATES = [[m
[31m-    {[m
[31m-        'BACKEND': 'django.template.backends.django.DjangoTemplates',[m
[31m-        'DIRS': ['pybo/templates'],[m
[31m-        'APP_DIRS': True,[m
[31m-        'OPTIONS': {[m
[31m-            'context_processors': [[m
[31m-                'django.template.context_processors.debug',[m
[31m-                'django.template.context_processors.request',[m
[31m-                'django.contrib.auth.context_processors.auth',[m
[31m-                'django.contrib.messages.context_processors.messages',[m
[31m-            ],[m
[31m-        },[m
[31m-    },[m
[31m-][m
[31m-[m
[31m-WSGI_APPLICATION = 'config.wsgi.application'[m
[31m-[m
[31m-[m
[31m-# Database[m
[31m-# https://docs.djangoproject.com/en/5.1/ref/settings/#databases[m
[31m-[m
[31m-DATABASES = {[m
[31m-    'default': {[m
[31m-        'ENGINE': 'django.db.backends.sqlite3',[m
[31m-        'NAME': BASE_DIR / 'db.sqlite3',[m
[31m-    }[m
[31m-}[m
[31m-[m
[31m-[m
[31m-# Password validation[m
[31m-# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators[m
[31m-[m
[31m-AUTH_PASSWORD_VALIDATORS = [[m
[31m-    {[m
[31m-        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',[m
[31m-    },[m
[31m-    {[m
[31m-        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',[m
[31m-    },[m
[31m-    {[m
[31m-        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',[m
[31m-    },[m
[31m-    {[m
[31m-        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',[m
[31m-    },[m
[31m-][m
[31m-[m
[31m-[m
[31m-# Internationalization[m
[31m-# https://docs.djangoproject.com/en/5.1/topics/i18n/[m
[31m-[m
[31m-LANGUAGE_CODE = 'ko-kr'[m
[31m-[m
[31m-TIME_ZONE = 'Asia/Seoul'[m
[31m-[m
[31m-USE_I18N = True[m
[31m-[m
[31m-USE_TZ = True[m
[31m-[m
[31m-[m
[31m-# Static files (CSS, JavaScript, Images)[m
[31m-# https://docs.djangoproject.com/en/5.1/howto/static-files/[m
[31m-[m
[31m-STATIC_URL = '/static/'[m
[31m-[m
[31m-# 개발 환경에서 사용할 Static 파일 경로 설정[m
[31m-STATICFILES_DIRS = [[m
[31m-    os.path.join(BASE_DIR, 'pybo', 'static'),[m
[31m-][m
[31m-[m
[31m-# 배포 환경에서 Static 파일을 모으는 디렉토리 (collectstatic 명령어 사용 시 필요)[m
[31m-STATIC_ROOT = BASE_DIR / 'staticfiles'[m
[31m-[m
[31m-# Default primary key field type[m
[31m-# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field[m
[31m-[m
[31m-DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'[m
[31m-[m
[31m-[m
[31m-LOGIN_REDIRECT_URL = '/'  # 로그인 성공 후 홈 페이지로 리다이렉트[m
[31m-LOGOUT_REDIRECT_URL = '/'  # 로그아웃 후 홈 페이지로 리다이렉트[m
[31m-[m
[31m-LOGIN_URL = '/login/'  # 로그인하지 않은 사용자가 접근 시 리다이렉트되는 URL[m
